### ISSUE TITLE
Why iproducer?

### ISSUE THREAD

**Issue by r-barnes** [zhouguiyun-uestc/ParallelFlowDirections#9]
It looks as though producer is the only class that inherits from iproducer (my apologies if I missed another). If so, can't you eliminate the iproducer class? It seems like unnecessary complexity.

**Comment by zhouguiyun-uestc** [comment]
This is a design pattern that is embraced by some people. It does add some complexity. But it should not add too much difficulty for people to understand the code.

**Comment by r-barnes** [comment]
Could you explain the reasoning?

**Comment by zhouguiyun-uestc** [comment]
The design pattern separates the interfaces from the implemention. For example, we can easily replace the current impelementation of ObjectaFactory in a separate module without making any changes to the codes in the main program, which emphasizes the communications among the producer and consumers.  When users  work on other algorithms, they can focus on the implementations of the producer and consumers instead of the communication part. 

As said in our previous comment, this is the preference of our implementions. It does not prevent others from using simpler design patterns.  It is just a choice of the programmers.

**Comment by r-barnes** [comment]
Thank you for the explanation.
